{% set name = "pytest-cov" %}
{% set version = "6.1.1" %}
{% set sha256 = "46935f7aaefba760e716c2ebfbe1c216240b9592966e7da99ea8292d4d3e2a0a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - pytest >=4.6
    - coverage >=7.5
    - toml

test:
  requires:
    - python {{ python_min }}
  commands:
    - pytest --traceconfig | grep pytest-cov-{{ version }}

about:
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin for measuring coverage
  dev_url: https://github.com/pytest-dev/pytest-cov

extra:
  recipe-maintainers:
    - dopplershift
    - nicoddemus
