{% set name = "pytest-cov" %}
{% set version = "6.3.0" %}
{% set sha256 = "35c580e7800f87ce892e687461166e1ac2bcb8fb9e13aea79032518d6e503ff2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - pytest >=6.2.5
    - coverage >=7.5
    - pluggy >=1.2
    - toml

test:
  requires:
    - python {{ python_min }}
  commands:
    - pytest --traceconfig | grep pytest-cov-{{ version }}

about:
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin for measuring coverage
  dev_url: https://github.com/pytest-dev/pytest-cov

extra:
  recipe-maintainers:
    - dopplershift
    - nicoddemus
