{% set name = "pytest-cov" %}
{% set version = "4.0.0" %}
{% set sha256 = "996b79efde6433cdbd0088872dbc5fb3ed7fe1578b68cdbba634f14bb8dd0470" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - pytest >=4.6
    - coverage >=5.2.1
    - toml

test:
  commands:
    - pytest --traceconfig | grep pytest-cov-{{ version }}

about:
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin for measuring coverage
  dev_url: https://github.com/pytest-dev/pytest-cov

extra:
  recipe-maintainers:
    - dopplershift
    - nicoddemus
