{% set name = "pytest-cov" %}
{% set version = "2.12.1" %}
{% set sha256 = "261ceeb8c227b726249b376b8526b600f38667ee314f910353fa318caa01f4d7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - setuptools
    - pytest >=4.6
    - coverage >=5.2.1

test:
  commands:
    - pytest --traceconfig | grep pytest-cov-{{ version }}

about:
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin for measuring coverage
  dev_url: https://github.com/pytest-dev/pytest-cov

extra:
  recipe-maintainers:
    - dopplershift
    - nicoddemus
